# Generated by Django 4.2.10 on 2024-02-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruct_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='image',
            field=models.ImageField(upload_to='processed_images/'),
        ),
    ]
